### ISSUE TITLE
CRA example request

### ISSUE THREAD

**Issue by phamthanhtrungg** [ladifire-opensource/stylex#14]
How do I use configure this package with create-react-app without eject the app `npm run eject`

**Comment by phamthanhtrungg** [comment]
![screenshot]()

**Comment by phamthanhtrungg** [comment]
<img width="1044" alt="Screen Shot 2021-02-15 at 23 27 09" src="https://user-images.githubusercontent.com/31823932/107971764-78370e00-6fe5-11eb-89ec-4d77400f5250.png">

**Comment by phamthanhtrungg** [comment]
I figured a way. We have to you craco js to extend cra default config and in **craco.config.js**
```js
module.exports = {
  babel: {
    plugins: [
      [
        '@ladifire-opensource/babel-plugin-transform-stylex',
        {
          inject: true, // will inject compiled css to stylesheet in head
        },
      ],
    ],
  },
};
```

**Comment by ladifire** [comment]
@phamthanhtrungg
Thanks, can you make a pull request for changing document in README.md?

**Comment by phamthanhtrungg** [comment]
@ladifire checkout my pr  #16

**Comment by ladifire** [comment]
@phamthanhtrungg please consider to add create-react-app example. It's should be placed in: ```packages/stylex-create-react-app-examples```

**Comment by phamthanhtrungg** [comment]
I will make a pr tomorrow
