### ISSUE TITLE
Improve type definition

### ISSUE THREAD

**Issue by ladifire** [ladifire-opensource/stylex#4]
Due to newest type definition update from @somibuon. We need improve this:

```js
const styles = stylex.create({
  root: {
    a: 150, // ??
    b: "foo", // ??
    width: 150,
    height: 150,
    backgroundColor: "red",
    color: "#fff",
    padding: 8,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 12,

    "@media (max-width: 899px)": {
      width: "100%",
    }
  },
})
```

We don't want "a: 150" still exits in our code, this is dead code. So we need to check for CSS Properties.

I think you need to take type from css.Properties.

With media query, you can define custom type, then extends the CSS Object type

```
"@media (max-width: 899px)": {
      width: "100%",
    }
```

**Comment by somibuon** [comment]
Please check the PR here: https://github.com/ladifire-opensource/stylex/pull/5

**Comment by ladifire** [comment]
@somibuon 
Please see bellow photo for our original definition. In your update, these warnings lost!
![New Project](https://user-images.githubusercontent.com/51266596/105045762-db8f5800-5a9a-11eb-8849-c6d24205e6af.jpg)
