### ISSUE TITLE
New ideas, improve project

### ISSUE THREAD

**Issue by phamthanhtrungg** [ladifire-opensource/stylex#6]
* Media query
```js
backgroundContainerDialog: {
    "@media (max-width: 899px)": {
      // TODO: check here, miss "a@media"
      height: "calc(50vh)",
    },
  },
```
Consider changing it to something like this
```js
backgroundContainerDialog: {
    [stylex.breakpoints.up('md')]: {
      // TODO: check here, miss "a@media"
      height: "calc(50vh)",
    },
  },
```
* Make command in **Package.json** commands more consise
```
 "scripts": {
    "run": "webpack --progress --watch", --> "start:watch": "webpack --progress --watch"
    "start:server": "node server.js"
  }
```
* Also, please consider using [husky](https://typicode.github.io/husky/) before commiting, there are so many liting errors
![Screen Shot 2021-01-20 at 11 38 19](https://user-images.githubusercontent.com/31823932/105127721-036ed200-5b14-11eb-869b-254e74b0db44.png)
![Screen Shot 2021-01-20 at 11 39 28](https://user-images.githubusercontent.com/31823932/105127813-33b67080-5b14-11eb-86f2-a386aaa02275.png)

**Comment by ladifire** [comment]
@phamthanhtrungg 

about your Media query idea, it's look like ```material-ui```, isn't it?. We's consider it as an option, but not replacement for native query string. So we can use:

native query string;

```
backgroundContainerDialog: {
    "@media ....": {
      height: "calc(50vh)",
    },
  },
```

or:

```
backgroundContainerDialog: {
    [stylex.breakpoints.up('md')]: {
      height: "calc(50vh)",
    },
  },
```

**Comment by phamthanhtrungg** [comment]
@ladifire Yes, it will be very helful if we have some extra stuff like material-ui: breakpoints,props, ...
